[package]
name = "breachops-nav"
version = "0.1.0"
edition = "2024"
authors.workspace = true
categories.workspace = true
keywords.workspace = true

[[bin]]
bench = false
path = "src/main.rs"
name = "bonav"

[dependencies]
